security:
    enable_authenticator_manager: true
    password_hashers:
        App\Infrastructure\Driven\Authentication\SecurityUser: 'auto'
    providers:
        app_user_provider:
            id: App\Infrastructure\Driven\Authentication\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_token:
            pattern: ^/token$
            security: false
        api:
            oauth2: true
            pattern: ^/api
            security: true
            stateless: true
        main:
            stateless: false
            form_login: ~
            custom_authenticators:
                - App\Infrastructure\Driven\Authentication\LoginAuthenticator
            entry_point: form_login
            logout:
                path: app_logout
    access_control:
        - { path: ^/authorize, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            App\Infrastructure\Driven\Authentication\SecurityUser:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
